// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package iio

import (
	"github.com/google/wire"
	"github.com/mattn/go-colorable"
	"io"
	"os"
)

// Injectors from inject.go:

func Inject() (*Service, error) {
	service := NewStdIO()
	return service, nil
}

// inject.go:

var Provider = wire.NewSet(
	NewStdIO,
)

var FlexProvider = wire.NewSet(
	New,
)

func New(o, e io.Writer, i io.Reader) *Service {
	return &Service{
		InR:  i,
		OutW: o,
		ErrW: e,
	}
}

// Stdio returns a standard IO object.
func NewStdIO() *Service {
	io2 := &Service{
		InR:  os.Stdin,
		OutW: colorable.NewColorableStdout(),
		ErrW: colorable.NewColorableStderr(),
	}

	return io2
}
