// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package iio

// Injectors from inject.go:

func NewIO() (*Service, error) {
	service := NewStdIO()
	return service, nil
}
